[[pages]]
path = "Homepage.py"
name = "LSBC"
icon = "ğŸ§­"

[[pages]]
path = "pages/0_Criador_de_Personagens.py"
name = "Criador de Personagens"
icon = "ğŸ§¬"
is_section = true

[[pages]]
path = "pages/1_Informacoes_Gerais.py"
name = "â†’ InformaÃ§Ãµes Gerais"
icon = "ğŸ§¾"

[[pages]]
path = "pages/2_Classe_e_Origem.py"
name = "â†’ Classe e Origem"
icon = "ğŸ§­"

[[pages]]
path = "pages/3_Atributos.py"
name = "â†’ Atributos"
icon = "ğŸ“Š"

[[pages]]
path = "pages/4_Habilidades.py"
name = "â†’ Habilidades"
icon = "ğŸ¯"

[[pages]]
path = "pages/5_Equipamentos.py"
name = "â†’ Equipamentos"
icon = "ğŸ§°"

[[pages]]
path = "pages/6_Truques.py"
name = "â†’ Truques"
icon = "âœ¨"

[[pages]]
path = "pages/7_Resumo.py"
name = "â†’ Resumo"
icon = "ğŸ“œ"
